version: "3.3"
services:
  db:
    build: .
    volumes:
      - db_vol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: testdb1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    restart: always

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Root

volumes:
      db_vol:
